spring:
  application:
    name: commentService
  datasource:
    url: jdbc:postgresql://localhost:5432/comment_db
    username: postgres
    password: Aman@3608
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
