spring:
  application:
    name: discoveryService

  datasource:
    url: jdbc:postgresql://localhost:5432/discovery_db
    username: postgres
    password: Aman@3608

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
