spring:
  application:
    name: taskService
  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    username: postgres
    password: Aman@3608
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka